In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("banking.csv")
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             41188 non-null  int64  
 1   job             41188 non-null  object 
 2   marital         41188 non-null  object 
 3   education       41188 non-null  object 
 4   default         41188 non-null  object 
 5   housing         41188 non-null  object 
 6   loan            41188 non-null  object 
 7   contact         41188 non-null  object 
 8   month           41188 non-null  object 
 9   day_of_week     41188 non-null  object 
 10  duration        41188 non-null  int64  
 11  campaign        41188 non-null  int64  
 12  pdays           41188 non-null  int64  
 13  previous        41188 non-null  int64  
 14  poutcome        41188 non-null  object 
 15  emp_var_rate    41188 non-null  float64
 16  cons_price_idx  41188 non-null  float64
 17  cons_conf_idx   41188 non-null 

In [3]:
df['education'].head()

0             basic.4y
1              unknown
2    university.degree
3          high.school
4             basic.4y
Name: education, dtype: object

In [4]:
df['job'].unique()

array(['blue-collar', 'technician', 'management', 'services', 'retired',
       'admin.', 'housemaid', 'unemployed', 'entrepreneur',
       'self-employed', 'unknown', 'student'], dtype=object)

In [5]:
df["job"].replace('blue-collar', 1, inplace=True)
df["job"].replace('technician', 2, inplace=True)
df["job"].replace('management', 3, inplace=True)
df["job"].replace('services', 4, inplace=True)
df["job"].replace('retired', 5, inplace=True)
df["job"].replace('admin.', 6, inplace=True)
df["job"].replace('housemaid', 7, inplace=True)
df["job"].replace('unemployed', 8, inplace=True)
df["job"].replace('entrepreneur', 9, inplace=True)
df["job"].replace('self-employed', 10, inplace=True)
df["job"].replace('unknown', 11, inplace=True)
df["job"].replace('student', 12, inplace=True)

In [6]:
df.head()

age  job  marital          education  default housing loan   contact month  \
0   44    1  married           basic.4y  unknown     yes   no  cellular   aug   
1   53    2  married            unknown       no      no   no  cellular   nov   
2   28    3   single  university.degree       no     yes   no  cellular   jun   
3   39    4  married        high.school       no      no   no  cellular   apr   
4   55    5  married           basic.4y       no     yes   no  cellular   aug   

  day_of_week  ...  campaign  pdays  previous     poutcome emp_var_rate  \
0         thu  ...         1    999         0  nonexistent          1.4   
1         fri  ...         1    999         0  nonexistent         -0.1   
2         thu  ...         3      6         2      success         -1.7   
3         fri  ...         2    999         0  nonexistent         -1.8   
4         fri  ...         1      3         1      success         -2.9   

   cons_price_idx  cons_conf_idx  euribor3m  nr_employed  y  
0          93.444          -36.1      4.963       5228.1  0  
1          93.200          -42.0      4.021       5195.8  0  
2          94.055          -39.8      0.729       4991.6  1  
3          93.075          -47.1      1.405       5099.1  0  
4          92.201          -31.4      0.869       5076.2  1  

[5 rows x 21 columns]

In [7]:
df['marital'].unique()

array(['married', 'single', 'divorced', 'unknown'], dtype=object)

In [8]:
df["marital"].replace('married', 1, inplace=True)
df["marital"].replace('single', 2, inplace=True)
df["marital"].replace('divorced', 3, inplace=True)
df["marital"].replace('unknown', 4, inplace=True)

In [9]:
df['education'].unique()

array(['basic.4y', 'unknown', 'university.degree', 'high.school',
       'basic.9y', 'professional.course', 'basic.6y', 'illiterate'],
      dtype=object)

In [10]:
dict={'basic.4y':1,'unknown':2,'university.degree':3,'high.school':4,'basic.9y':5,'professional.course':6,'basic.6y':7,'illiterate':8}

In [11]:
df['education']=df['education'].map(dict)

In [12]:
df['default'].unique()

array(['unknown', 'no', 'yes'], dtype=object)

In [13]:
df["default"].replace('unknown', 1, inplace=True)
df["default"].replace('no', 2, inplace=True)
df["default"].replace('yes', 3, inplace=True)


In [14]:
df['poutcome'].unique()

array(['nonexistent', 'success', 'failure'], dtype=object)

In [15]:
df['poutcome'].replace('nonexistent', 1, inplace=True)
df['poutcome'].replace('success', 2, inplace=True)
df['poutcome'].replace('failure', 3, inplace=True)


In [16]:
df['housing'].unique()

array(['yes', 'no', 'unknown'], dtype=object)

In [17]:
df['housing'].replace('yes',1,inplace=True)
df['housing'].replace('no',2,inplace=True)
df['housing'].replace('unknown',3,inplace=True)

In [18]:
df['loan'].unique()

array(['no', 'yes', 'unknown'], dtype=object)

In [19]:
df['loan'].replace('no',1,inplace=True)
df['loan'].replace('yes',2,inplace=True)
df['loan'].replace('unknown',3,inplace=True)

In [20]:
df['contact'].unique()

array(['cellular', 'telephone'], dtype=object)

In [21]:
df['contact'].replace('cellular',1,inplace=True)
df['contact'].replace('telephone',2,inplace=True)

In [22]:
df['month'].unique()

array(['aug', 'nov', 'jun', 'apr', 'jul', 'may', 'oct', 'mar', 'sep',
       'dec'], dtype=object)

In [23]:
dict1={'aug':1,'nov':2,'jun':3,'apr':4,'jul':5,'may':6,'oct':7,'mar':8,'sep':9,'dec':10}

In [24]:
df['month']=df['month'].map(dict1)

In [25]:
df['day_of_week'].unique()

array(['thu', 'fri', 'tue', 'mon', 'wed'], dtype=object)

In [26]:
dict2={'thu':1,'fri':2,'tue':3,'mon':4,'wed':5}

In [27]:
df['day_of_week']=df['day_of_week'].map(dict2)

In [28]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             41188 non-null  int64  
 1   job             41188 non-null  int64  
 2   marital         41188 non-null  int64  
 3   education       41188 non-null  int64  
 4   default         41188 non-null  int64  
 5   housing         41188 non-null  int64  
 6   loan            41188 non-null  int64  
 7   contact         41188 non-null  int64  
 8   month           41188 non-null  int64  
 9   day_of_week     41188 non-null  int64  
 10  duration        41188 non-null  int64  
 11  campaign        41188 non-null  int64  
 12  pdays           41188 non-null  int64  
 13  previous        41188 non-null  int64  
 14  poutcome        41188 non-null  int64  
 15  emp_var_rate    41188 non-null  float64
 16  cons_price_idx  41188 non-null  float64
 17  cons_conf_idx   41188 non-null 

age  job  marital  education  default  housing  loan  contact  month  \
0   44    1        1          1        1        1     1        1      1   
1   53    2        1          2        2        2     1        1      2   
2   28    3        2          3        2        1     1        1      3   
3   39    4        1          4        2        2     1        1      4   
4   55    5        1          1        2        1     1        1      1   

   day_of_week  ...  campaign  pdays  previous  poutcome  emp_var_rate  \
0            1  ...         1    999         0         1           1.4   
1            2  ...         1    999         0         1          -0.1   
2            1  ...         3      6         2         2          -1.7   
3            2  ...         2    999         0         1          -1.8   
4            2  ...         1      3         1         2          -2.9   

   cons_price_idx  cons_conf_idx  euribor3m  nr_employed  y  
0          93.444          -36.1      4.963       5228.1  0  
1          93.200          -42.0      4.021       5195.8  0  
2          94.055          -39.8      0.729       4991.6  1  
3          93.075          -47.1      1.405       5099.1  0  
4          92.201          -31.4      0.869       5076.2  1  

[5 rows x 21 columns]

In [29]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [30]:
X

age  job  marital  education  default  housing  loan  contact  month  \
0       44    1        1          1        1        1     1        1      1   
1       53    2        1          2        2        2     1        1      2   
2       28    3        2          3        2        1     1        1      3   
3       39    4        1          4        2        2     1        1      4   
4       55    5        1          1        2        1     1        1      1   
...    ...  ...      ...        ...      ...      ...   ...      ...    ...   
41183   59    5        1          4        1        2     2        2      3   
41184   31    7        1          1        1        2     1        2      6   
41185   42    6        2          3        1        1     2        2      6   
41186   48    2        1          6        2        2     2        2      7   
41187   25   12        2          4        2        2     1        2      6   

       day_of_week  duration  campaign  pdays  previous  poutcome  \
0                1       210         1    999         0         1   
1                2       138         1    999         0         1   
2                1       339         3      6         2         2   
3                2       185         2    999         0         1   
4                2       137         1      3         1         2   
...            ...       ...       ...    ...       ...       ...   
41183            1       222         1    999         0         1   
41184            1       196         2    999         0         1   
41185            5        62         3    999         0         1   
41186            3       200         2    999         0         1   
41187            2       112         4    999         0         1   

       emp_var_rate  cons_price_idx  cons_conf_idx  euribor3m  nr_employed  
0               1.4          93.444          -36.1      4.963       5228.1  
1              -0.1          93.200          -42.0      4.021       5195.8  
2              -1.7          94.055          -39.8      0.729       4991.6  
3              -1.8          93.075          -47.1      1.405       5099.1  
4              -2.9          92.201          -31.4      0.869       5076.2  
...             ...             ...            ...        ...          ...  
41183           1.4          94.465          -41.8      4.866       5228.1  
41184           1.1          93.994          -36.4      4.860       5191.0  
41185           1.1          93.994          -36.4      4.857       5191.0  
41186          -3.4          92.431          -26.9      0.742       5017.5  
41187           1.1          93.994          -36.4      4.859       5191.0  

[41188 rows x 20 columns]

In [31]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

In [32]:
scalar=StandardScaler()
X=scalar.fit_transform(X)
    

In [33]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)
classifier= LogisticRegression(random_state=0)
classifier.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [34]:
cm=confusion_matrix(y_test,classifier.predict(X_test))
print(cm)
print(classifier.score(X_test,y_test)*100)
    

[[8922  234]
 [ 670  471]]
91.22074390599204


In [35]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)
rfc= RandomForestClassifier(random_state=0)
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [36]:
cm=confusion_matrix(y_test,rfc.predict(X_test))
print(cm)
print(rfc.score(X_test,y_test)*100)
    

[[8847  309]
 [ 563  578]]
91.53151403321355


In [37]:
#feature selection
from sklearn.decomposition import PCA


In [56]:
pca=PCA(n_components=15)
fit=pca.fit(X)

#summarize components
print(f"Explained variance: {fit.explained_variance_ratio_}")

Explained variance: [0.23065192 0.07902868 0.07014685 0.06309197 0.06186241 0.06004933
 0.05392955 0.05058455 0.04964744 0.04555627 0.04372853 0.03967822
 0.03798127 0.03638161 0.03464465]


In [57]:
Xbest=pca.fit_transform(X)

In [58]:
trainx,testx,trainy,testy=train_test_split(Xbest,y,test_size=0.2,random_state=0)
model=LogisticRegression()
model.fit(trainx,trainy)
ypred=model.predict(testx)
print(model.score(testx,testy))
print(confusion_matrix(testy,ypred))

0.911143481427531
[[7140  185]
 [ 547  366]]
